# Generated by Django 4.0.4 on 2022-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
